spring:
  application:
    name: inventory-service

  datasource:
    url: jdbc:postgresql://localhost:5432/inventory_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations:
      - db/migration

  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      properties:
        spring.json.trusted.packages: "*"

jwt:
  secret: d2hhdGV2ZXJ5bG9uZ3NlY3JldGtleWZvcmp3dHRvazE=

server:
  port: 8086
