spring:
  application:
    name: shipping-service
  datasource:
    url: jdbc:postgresql://localhost:5432/shipping_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations:
      - db/migration

server:
  port: 8087
