### Create payment
POST http://localhost:8085/api/payments
Content-Type: application/json

{
  "orderId": "8ecd9468-a8bd-4868-a9b1-f82296a0b61a",
  "userId": "7eecc8f3-a7eb-4753-b5bf-9eac7c7ac987",
  "paymentMethod": "BANK_TRANSFER"
}

### Get payment by ID
GET http://localhost:8085/api/payments/242b0557-4a1f-4d8a-9881-ab917fe94ad2

### Get payment by order ID
GET http://localhost:8085/api/payments/order/8ecd9468-a8bd-4868-a9b1-f82296a0b61a

### Update status to COMPLETED
PATCH http://localhost:8085/api/payments/242b0557-4a1f-4d8a-9881-ab917fe94ad2/status
Content-Type: application/json

{
  "status": "COMPLETED"
}

### Update status to FAILED
PATCH http://localhost:8085/api/payments/669fca92-809c-4364-8413-72e449f4b9ee/status
Content-Type: application/json

{
  "status": "FAILED"
}

### Refund payment (harus status COMPLETED)
POST http://localhost:8085/api/payments/669fca92-809c-4364-8413-72e449f4b9ee/refund