### Add item to cart
POST http://localhost:8080/api/cart/7eecc8f3-a7eb-4753-b5bf-9eac7c7ac987/items
Content-Type: application/json

{
  "productId": "8af644c0-ef5f-40fe-a78f-b190f072002b",
  "quantity": 1
}

### Get user's cart
GET http://localhost:8080/api/cart/7eecc8f3-a7eb-4753-b5bf-9eac7c7ac987

### Get all products
GET http://localhost:8080/api/product

### Create order
POST http://localhost:8080/api/order
Content-Type: application/json

{
  "userId": "7eecc8f3-a7eb-4753-b5bf-9eac7c7ac987",
  "shippingAddress": "Somewhere",
  "notes": "Gak pedes"
}

### Create payment
POST http://localhost:8080/api/payment
Content-Type: application/json

{
  "orderId": "5138b392-d65c-4f89-a1f4-361c77cc8a6f",
  "userId": "7eecc8f3-a7eb-4753-b5bf-9eac7c7ac987",
  "paymentMethod": "BANK_TRANSFER"
}

### Update status to COMPLETED
PATCH http://localhost:8080/api/payment/482c0fba-556b-425d-b393-b328f738c803/status
Content-Type: application/json

{
  "status": "COMPLETED"
}