### Add item to cart
POST http://localhost:8080/api/cart/7eecc8f3-a7eb-4753-b5bf-9eac7c7ac987/items
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI3ZWVjYzhmMy1hN2ViLTQ3NTMtYjViZi05ZWFjN2M3YWM5ODciLCJlbWFpbCI6InVzZXJAZW1haWwuY29tIiwicm9sZSI6IlJPTEVfVVNFUiIsImlhdCI6MTc4NTU1NjY1MiwiZXhwIjoxNzg1NTU3NTUyfQ.sWme-LIIYOPkiyhJNrVb3yjuMR7u3F5PtQL7N7tFD88
Content-Type: application/json

{
  "productId": "8af644c0-ef5f-40fe-a78f-b190f072002b",
  "quantity": 1
}

### Get user's cart
GET http://localhost:8080/api/cart/7eecc8f3-a7eb-4753-b5bf-9eac7c7ac987
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI3ZWVjYzhmMy1hN2ViLTQ3NTMtYjViZi05ZWFjN2M3YWM5ODciLCJlbWFpbCI6InVzZXJAZW1haWwuY29tIiwicm9sZSI6IlJPTEVfVVNFUiIsImlhdCI6MTc4NTU1NjY1MiwiZXhwIjoxNzg1NTU3NTUyfQ.sWme-LIIYOPkiyhJNrVb3yjuMR7u3F5PtQL7N7tFD88

### Get all products
GET http://localhost:8080/api/product

### Create order
POST http://localhost:8080/api/order
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI3ZWVjYzhmMy1hN2ViLTQ3NTMtYjViZi05ZWFjN2M3YWM5ODciLCJlbWFpbCI6InVzZXJAZW1haWwuY29tIiwicm9sZSI6IlJPTEVfVVNFUiIsImlhdCI6MTc4NTU1NjY1MiwiZXhwIjoxNzg1NTU3NTUyfQ.sWme-LIIYOPkiyhJNrVb3yjuMR7u3F5PtQL7N7tFD88
Content-Type: application/json

{
  "userId": "7eecc8f3-a7eb-4753-b5bf-9eac7c7ac987",
  "shippingAddress": "Somewhere",
  "notes": "Gak pedes"
}

### Update order status
PATCH http://localhost:8080/api/order/981994e4-f1c8-4169-93cb-3fce84884566/status
Content-Type: application/json

{
  "status": "CANCELED"
}

### Create payment
POST http://localhost:8080/api/payment
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI3ZWVjYzhmMy1hN2ViLTQ3NTMtYjViZi05ZWFjN2M3YWM5ODciLCJlbWFpbCI6InVzZXJAZW1haWwuY29tIiwicm9sZSI6IlJPTEVfVVNFUiIsImlhdCI6MTc4NTU1NjY1MiwiZXhwIjoxNzg1NTU3NTUyfQ.sWme-LIIYOPkiyhJNrVb3yjuMR7u3F5PtQL7N7tFD88
Content-Type: application/json

{
  "orderId": "656b8e20-c114-4e63-8331-5bc0a48509bd",
  "userId": "7eecc8f3-a7eb-4753-b5bf-9eac7c7ac987",
  "paymentMethod": "BANK_TRANSFER"
}

### Update status to COMPLETED
PATCH http://localhost:8080/api/payment/abcfb314-9c64-42ef-b7d5-77f554e993a8/status
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI3ZWVjYzhmMy1hN2ViLTQ3NTMtYjViZi05ZWFjN2M3YWM5ODciLCJlbWFpbCI6InVzZXJAZW1haWwuY29tIiwicm9sZSI6IlJPTEVfVVNFUiIsImlhdCI6MTc4NTU1NjY1MiwiZXhwIjoxNzg1NTU3NTUyfQ.sWme-LIIYOPkiyhJNrVb3yjuMR7u3F5PtQL7N7tFD88
Content-Type: application/json

{
  "status": "COMPLETED"
}