@token = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI3ZWVjYzhmMy1hN2ViLTQ3NTMtYjViZi05ZWFjN2M3YWM5ODciLCJlbWFpbCI6InVzZXJAZW1haWwuY29tIiwicm9sZSI6IlJPTEVfVVNFUiIsImlhdCI6MTc4Njg1Njg2NSwiZXhwIjoxNzg2ODU3NzY1fQ.ifuyRtcwK4zWPdhZd7b0-U-fUj-tXVKWmQDE_y835MA

### Login user
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "user@email.com",
  "password": "user"
}

### Add item to cart
POST http://localhost:8080/api/cart/7eecc8f3-a7eb-4753-b5bf-9eac7c7ac987/items
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "productId": "8af644c0-ef5f-40fe-a78f-b190f072002b",
  "quantity": 1
}

### Get user's cart
GET http://localhost:8080/api/cart/7eecc8f3-a7eb-4753-b5bf-9eac7c7ac987
Authorization: Bearer {{token}}

### Get all products
GET http://localhost:8080/api/product
Authorization: Bearer {{token}}

### Get a product
GET http://localhost:8080/api/product/6790fb5f-8e63-49b3-8fb3-0a634b1d73f1
Authorization: Bearer {{token}}

### Search a product
GET http://localhost:8080/api/product/search?q=samsun
Authorization: Bearer {{token}}

### Create product
POST http://localhost:8080/api/product
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Samsung S25",
  "description": "Mantap",
  "stock": 10,
  "price": 29.99
}

### Update a product
PUT http://localhost:8080/api/product/8af644c0-ef5f-40fe-a78f-b190f072002b
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Laptop Acer",
  "description": "Laptop buat gaming cuy",
  "price": 48.99,
  "stock": 9
}

### Delete a product
DELETE http://localhost:8080/api/product/28ab4675-7eca-49e2-96bc-d0e0e7472523
Authorization: Bearer {{token}}

### Create order
POST http://localhost:8080/api/order
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "userId": "7eecc8f3-a7eb-4753-b5bf-9eac7c7ac987",
  "shippingAddress": "Somewhere",
  "notes": "Gak pedes"
}

### Update order status
PATCH http://localhost:8080/api/order/981994e4-f1c8-4169-93cb-3fce84884566/status
Content-Type: application/json

{
  "status": "CANCELED"
}

### Create payment
POST http://localhost:8080/api/payment
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "orderId": "ebfe33a4-bf80-48a3-8ae7-15f674512b71",
  "userId": "7eecc8f3-a7eb-4753-b5bf-9eac7c7ac987",
  "paymentMethod": "BANK_TRANSFER"
}

### Update status to COMPLETED
PATCH http://localhost:8080/api/payment/806d242e-0e7f-4461-a254-0a4adb29aec8/status
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "status": "COMPLETED"
}

### Logstash
GET http://localhost:9200/_cluster/health

### Logstash
GET http://localhost:9200/_cat/indices

### Elasticsearch
GET http://localhost:9200/products/_count

### Elasticsearch
GET http://localhost:9200/products/_search?pretty