spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:postgresql://localhost:5432/payment_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations:
      - db/migration

  kafka:
    bootstrap-servers: localhost:29092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

jwt:
  secret: d2hhdGV2ZXJ5bG9uZ3NlY3JldGtleWZvcmp3dHRvazE=

internal:
  auth:
    service: payment-service

server:
  port: 8085

services:
  order-service:
    url: ${ORDER_SERVICE_URL:http://localhost:8084}

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus