spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://localhost:5432/order_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations:
      - db/migration

server:
  port: 8084

services:
  cart-service:
    url: http://localhost:8083
  inventory-service:
    url: http://localhost:8086
